include: /.gitlab/common.yml

.f:workflow_rules:
  - changes: [game-frontend/**/*]

f:build:
  extends: .build_job
  needs: []
  rules: !reference [.f:workflow_rules]
  variables:
    IMAGE_SUFFIX: game-frontend
  before_script:
    - cd game-frontend

f:container_scanning:
  extends: .container_scanning_job
  needs: [f:build]
  rules: !reference [f:build, rules]
  variables:
    IMAGE_SUFFIX: game-frontend
  artifacts:
    expose_as: Frontend container scanning

f:test_e2e_quality:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/cypress/browsers:node14.19.0-chrome100-ff99-edge
  stage: test
  needs: []
  rules: !reference [.f:workflow_rules]
  before_script:
    - cd game-frontend
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run test:ci
    - npm run e2e:ci
    - npm run lint:ci
  artifacts:
    when: always
    paths:
      - game-frontend/cypress/videos/
      - game-frontend/cypress/screenshots/
      - game-frontend/eslint-report.xml
    reports:
      junit:
        - game-frontend/tests/junit-test-results.xml
        - game-frontend/test-results.xml
      coverage_report:
        coverage_format: cobertura
        path: game-frontend/coverage/cobertura.xml
  cache:
    - key:
        files:
          - game-frontend/package-lock.json
      paths:
        - game-frontend/.npm/
    - key: eslint
      paths:
        - game-frontend/.eslintcache

f:code_quality-report:
  stage: .post
  needs: [f:test_e2e_quality]
  rules: !reference [f:test_e2e_quality, rules]
  variables:
    GIT_STRATEGY: none
  when: always
  allow_failure: true
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/guillaumejchauveau/checkstyle-report-codeclimate
  before_script:
    - cd game-frontend
  script: |
    cat eslint-report.xml \
      | python /opt/checkstyle-report-codeclimate.py \
      > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: game-frontend/gl-code-quality-report.json
