workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - build
  - check
  - report
  - deploy
  - cleanup

include:
  - /game-backend/.gitlab-ci.yml
  - /game-frontend/.gitlab-ci.yml
