apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring
  namespace: monitoring
  labels:
    app.kubernetes.io/name: monitoring-cluster_role
    app.kubernetes.io/part-of: monitoring.ops
    app.kubernetes.io/component: rbac
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring
  namespace: monitoring
  labels:
    app.kubernetes.io/name: monitoring-cluster_role-binding
    app.kubernetes.io/part-of: monitoring.ops
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring
subjects:
  - kind: ServiceAccount
    name: default
    namespace: monitoring
