apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
      annotations:
        ops/logs.scrape: 'true'
        ops/metrics.scrape: 'true'
        ops/metrics.port: '9464'
    spec:
      containers:
        - name: backend
          image: backend
          imagePullPolicy: Always
          env:
            - name: OTEL_SERVICE_NAME
              value:
            - name: OTEL_RESOURCE_ATTRIBUTES
              value:
            - name: OTEL_TRACES_EXPORTER
              value: jaeger
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: http://tempo.monitoring.svc.cluster.local:14250
          ports:
            - name: api
              containerPort: 4444
            - name: metrics
              containerPort: 9464
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: 4444
      targetPort: 4444
  selector:
    app.kubernetes.io/name: backend
