apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: client
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
      annotations:
        ops/logs.scrape: 'true'
        ops/metrics.scrape: 'true'
        ops/metrics.port: '9113'
    spec:
      containers:
        - name: frontend
          image: frontend
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
        - name: metrics
          image: nginx/nginx-prometheus-exporter
          args:
            - -nginx.scrape-uri=http://localhost:8081/nginx_status
          ports:
            - name: metrics
              containerPort: 9113
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: client
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: frontend
