apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - rbac.yml
namespace: monitoring
patches:
  - patch: |-
      - op: add
        path: /subjects/0/namespace
        value: monitoring
    target:
      kind: ClusterRoleBinding
      name: monitoring
  - patch: |-
      - op: add
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30300
    target:
      kind: Service
      name: grafana
