apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    app.kubernetes.io/name: grafana-config
    app.kubernetes.io/component: configuration
data:
  grafana.ini: |
    [feature_toggles]
    enable = tempoSearch tempoBackendSearch tempoApmTable
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    app.kubernetes.io/name: grafana-datasources
    app.kubernetes.io/component: configuration
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://prometheus:9090/
        access: proxy
        jsonData:
          exemplarTraceIdDestinations:
          - name: traceID
            datasourceUid: tempo
      - name: Loki
        type: loki
        uid: loki
        url: http://loki:3100
        orgId: 1
        apiVersion: 1
        access: proxy
        jsonData:
          derivedFields:
            - name: TraceID
              datasourceUid: tempo
              matcherRegex: (?:traceID|trace_id)=(\w+)
              url: $${__value.raw}
      - name: Tempo
        type: tempo
        uid: tempo
        url: http://tempo:3100
        access: proxy
        jsonData:
          httpMethod: GET
          serviceMap:
            datasourceUid: prometheus
          tracesToLogs:
            datasourceUid: loki
            tags: ['pod', 'namespace']
