apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: metric-aggregation
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
      annotations:
        ops/logs.scrape: 'true'
        ops/metrics.scrape: 'true'
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.40.4
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --enable-feature=exemplar-storage
            - --web.enable-remote-write-receiver
          ports:
            - containerPort: 9090
              name: http
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /-/ready
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
        - name: configmap-reload
          image: jimmidyson/configmap-reload:v0.5.0
          args:
            - --volume-dir=/etc/config
            - --webhook-url=http://127.0.0.1:9090/-/reload
          volumeMounts:
            - name: config
              mountPath: /etc/config
              readOnly: true
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: metric-aggregation
spec:
  ports:
    - name: http
      port: 9090
      targetPort: http
  selector:
    app.kubernetes.io/name: prometheus
