apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/component: trace-aggregation
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tempo
      annotations:
        ops/logs.scrape: 'true'
        ops/metrics.scrape: 'true'
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:1.5.0
          args:
            - -config.file=/etc/tempo/config.yml
          ports:
            - containerPort: 3100
              name: api
              protocol: TCP
            - containerPort: 14268
              name: http-ingest
              protocol: TCP
            - containerPort: 14250
              name: grpc-ingest
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/tempo/
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: api
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
      volumes:
        - name: config
          configMap:
            name: tempo-config
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/component: trace-aggregation
spec:
  ports:
    - name: api
      port: 3100
      targetPort: api
    - name: http-ingest
      port: 14268
      targetPort: http-ingest
    - name: grpc-ingest
      port: 14250
      targetPort: grpc-ingest
  selector:
    app.kubernetes.io/name: tempo
