apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  labels:
    app.kubernetes.io/name: tempo-config
    app.kubernetes.io/component: configuration
data:
  config.yml: |
    search_enabled: true
    metrics_generator_enabled: true
    usage_report:
      reporting_enabled: false

    server:
      http_listen_port: 3100

    distributor:
      receivers:
        jaeger:
          protocols:
            thrift_http:
            grpc:
            thrift_binary:
            thrift_compact:
        zipkin:
        otlp:
          protocols:
            http:
            grpc:
        opencensus:

    metrics_generator:
      storage:
        path: /tmp/tempo/
        remote_write:
          - url: http://prometheus:9090/api/v1/write

    storage:
      trace:
        backend: local
        wal:
          path: /var/tempo/wal
        local:
          path: /var/tempo/traces

    overrides:
      metrics_generator_processors: [service-graphs, span-metrics]
